# Generated by Django 4.0.4 on 2022-10-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0004_task_activity_task_description_task_order_task_phase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='total_tasks',
        ),
    ]
