# Generated by Django 4.0.4 on 2022-10-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0005_remove_task_total_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='couch_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='couch_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
