# Generated by Django 4.0.4 on 2022-10-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0006_activity_couch_id_task_couch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='form',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
