# Generated by Django 4.0.4 on 2023-08-09 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager', '0008_formtype_formfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['idx']},
        ),
        migrations.AddField(
            model_name='formfield',
            name='help_text',
            field=models.CharField(blank=True, help_text='Text to be displayed as help', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='idx',
            field=models.PositiveSmallIntegerField(default=1, help_text='Order in form'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='options',
            field=models.TextField(blank=True, help_text='For Select, enter list of Options, each on a new line.', null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='page',
            field=models.PositiveSmallIntegerField(default=1, help_text='Page to appear in form'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='required',
            field=models.BooleanField(default=False, help_text='Is the field mandatory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='form_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='process_manager.formtype'),
        ),
        migrations.AddField(
            model_name='task',
            name='form_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='process_manager.formtype'),
        ),
    ]
