# Generated by Django 4.0.4 on 2023-08-10 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('process_manager', '0009_alter_formfield_options_formfield_help_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachments_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('Data', 'Data'), ('Check', 'Check'), ('Integer', 'Integer'), ('Float', 'Float'), ('Select', 'Select'), ('Small Text', 'Small Text'), ('Text', 'Text')], help_text='Type of field', max_length=140),
        ),
        migrations.CreateModel(
            name='AttachmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Unique name for the Attachment', max_length=140)),
                ('file_type', models.CharField(choices=[('Image', 'Image'), ('Document', 'Document')], max_length=256)),
                ('order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='task',
            name='attachments',
            field=models.ManyToManyField(to='process_manager.attachmenttype'),
        ),
    ]
