# Generated by Django 4.0.4 on 2022-05-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_sql_user', models.CharField(max_length=150, unique=True)),
                ('no_sql_pass', models.CharField(max_length=128)),
                ('no_sql_db_name', models.CharField(max_length=150, unique=True)),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='code')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Facilitator',
                'verbose_name_plural': 'Facilitators',
            },
        ),
    ]
