# Generated by Django 4.0.4 on 2022-10-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='test_mode',
            field=models.BooleanField(default=False, verbose_name='test mode'),
        ),
    ]
