# Generated by Django 4.0.4 on 2023-03-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_facilitator_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='code'),
        ),
    ]
